name: Build and Deploy Collection
on:
  release:
    types:
      - published

jobs:
  build-and-deploy:
    permissions:
      contents: read
    steps:
      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_TOKEN }}'
