name: Deploy Collection to galaxy
on:
  release:
    types:
      - published

jobs:
  release_galaxy:
    uses: ansible/ansible-content-actions/.github/workflows/release_galaxy.yaml@main
    with:
      environment: release
    secrets:
      ah_token: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
